### ISSUE TITLE
request: auto-close gates!

### ISSUE THREAD

**Issue by rowantobias** [HeladoDeBrownie/Caves-of-Qud-Minimods#3]
as i was suggested to, here is my post!

i would love a mod for auto-closing gates ive opened as i pass through. usual use-case is when i am auto-exploring the stilt, i open the gates and all the animals get out... oops! something i can turn on and forget would be great

**Comment by HeladoDeBrownie** [comment]
note to self:

this can probably be done by adding a part to gates that listens for `ObjectLeavingCellEvent` and mirrors the check for opening a door when a creature bumps it

**Comment by HeladoDeBrownie** [comment]
resolved by 5fb96cdd326746962603672b6d6494de038c7cb0
